### ISSUE TITLE
azurerm provider could be removed

### ISSUE THREAD

**Issue by lkurzyniec** [claranet/terraform-azurerm-regions#5]
Why this module has declared `azurerm` provider? It doesn't need it at all.
This redundant dependency makes this module slower, because terraform needs to download it during init process.

**Comment by rossifumax** [comment]
**Hello,**

You're right, no need to declare a `required_provider` here.
We haven't seen this before, because we always use this module in Azure terraform stacks, so we always need the AzureRM provider.

We'll remove it and keep you informed !

Thanks for this issue :slightly_smiling_face:

**Comment by rossifumax** [comment]
That's it ! 
You've got the [v5.1.0](https://github.com/claranet/terraform-azurerm-regions/releases/tag/v5.1.0) available for it !

Thanks for this issue !
